/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Schema for OSS-IQ project metrics export data (v1.2 adds constraint_type and constraint_source_file)
 */
export interface OSSIQExportSchemaV12 {
  /**
   * Metadata about the export itself
   */
  metadata: {
    /**
     * Version of the export schema format
     */
    schema_version: "1.2";
    /**
     * UTC timestamp when the export was generated
     */
    export_timestamp: string;
    [k: string]: unknown;
  };
  /**
   * Basic project information
   */
  project: {
    /**
     * Project name
     */
    name: string;
    /**
     * Absolute path to the project
     */
    path: string;
    /**
     * Package registry type (npm, pypi, etc.)
     */
    registry: "npm" | "pypi";
    [k: string]: unknown;
  };
  /**
   * Summary statistics for the scanned project
   */
  summary: {
    /**
     * Total number of packages (production + development)
     */
    total_packages: number;
    /**
     * Number of production dependencies
     */
    production_packages: number;
    /**
     * Number of development dependencies
     */
    development_packages: number;
    /**
     * Number of packages with known CVEs
     */
    packages_with_cves: number;
    /**
     * Total number of CVEs across all packages
     */
    total_cves: number;
    /**
     * Number of packages behind the latest version
     */
    packages_outdated: number;
    [k: string]: unknown;
  };
  /**
   * Production dependency metrics
   */
  production_packages: PackageMetrics[];
  /**
   * Development dependency metrics
   */
  development_packages: PackageMetrics[];
  /**
   * Transitive dependency metrics (all paths, production edges only)
   */
  transitive_packages: PackageMetrics[];
  [k: string]: unknown;
}
/**
 * Metrics for a single package
 */
export interface PackageMetrics {
  /**
   * Package name (canonical registry name)
   */
  package_name: string;
  /**
   * Alias name as declared in the project manifest (null or same as package_name when no alias is used)
   */
  dependency_name?: string | null;
  /**
   * Whether this is a development/optional dependency
   */
  is_optional_dependency: boolean;
  /**
   * Currently installed version
   */
  installed_version: string;
  /**
   * Latest available version
   */
  latest_version: string | null;
  /**
   * Days between installed and latest version
   */
  time_lag_days: number | null;
  /**
   * Number of releases between installed and latest
   */
  releases_lag: number | null;
  /**
   * Known CVEs for this package
   */
  cve: CVEInfo[];
  /**
   * Ancestor chain from root to this package (null for direct dependencies)
   */
  dependency_path?: string[] | null;
  /**
   * Version constraint declared in the project manifest (e.g. '^1.2.3', '>=1.0,<2.0')
   */
  version_constraint?: string | null;
  /**
   * Source code repository URL
   */
  repo_url?: string | null;
  /**
   * Package homepage URL
   */
  homepage_url?: string | null;
  /**
   * Package registry page URL
   */
  package_url?: string | null;
  /**
   * SPDX license identifiers parsed from the package license expression
   */
  license?: string[] | null;
  /**
   * Package URL (PURL) per ECMA-386, e.g. pkg:pypi/requests@2.25.1 or pkg:npm/lodash@4.17.21
   */
  purl?: string | null;
  /**
   * How the version constraint was applied: DECLARED (loose/default spec), NARROWED (explicit range with bounds), PINNED (exact version), ADDITIVE (narrows via constraints file), or OVERRIDE (forces a version regardless of other requirements)
   */
  constraint_type?: "DECLARED" | "NARROWED" | "PINNED" | "ADDITIVE" | "OVERRIDE" | null;
  /**
   * File that introduced a non-DECLARED constraint (e.g. 'package.json' for npm overrides, 'pyproject.toml' for uv, 'requirements.txt' for pip classic)
   */
  constraint_source_file?: string | null;
  /**
   * PyPI extras requested for this dependency (e.g. ["security", "tests"] from requests[security,tests]); null for non-PyPI or when no extras are used
   */
  extras?: string[] | null;
  [k: string]: unknown;
}
/**
 * CVE information for a package
 */
export interface CVEInfo {
  /**
   * Primary CVE identifier
   */
  id: string;
  /**
   * All aliases (CVE, GHSA, OSV)
   */
  cve_ids: string[];
  /**
   * CVE database source
   */
  source: string;
  /**
   * Affected package name
   */
  package_name: string;
  /**
   * Package registry (npm, pypi, etc.)
   */
  package_registry: string;
  /**
   * Vulnerability description
   */
  summary: string;
  /**
   * Severity level
   */
  severity: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
  /**
   * List of affected versions
   */
  affected_versions: string[];
  /**
   * Publication date
   */
  published: string | null;
  /**
   * URL to upstream advisory
   */
  link: string;
  [k: string]: unknown;
}
