/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Schema for OSS-IQ project metrics export data (v1.5 adds epss to PackageMetrics, TransitivePackageMetrics and CVEInfo, runs_code_at_install/install_execution_reason to PackageMetrics and TransitivePackageMetrics, fix_age_days to CVEInfo, project_epss/packages_with_epss/packages_with_unscored_cves to summary, declares update_transitive_impacts, and replaces the phi_i/phi_p/phi_a CSI channels with the maintenance-state model: maintenance_state, maintenance_risk, maintenance_coverage, flow_trend, deprecation_signals and deprecation_successor on PackageMetrics and TransitivePackageMetrics, and packages_unmaintained/packages_deprecated on summary)
 */
export interface OSSIQExportSchemaV15 {
  /**
   * Metadata about the export itself
   */
  metadata: {
    /**
     * Version of the export schema format
     */
    schema_version: "1.5";
    /**
     * UTC timestamp when the export was generated
     */
    export_timestamp: string;
    [k: string]: unknown;
  };
  /**
   * Basic project information
   */
  project: {
    /**
     * Project name
     */
    name: string;
    /**
     * Absolute path to the project
     */
    path: string;
    /**
     * Package registry type (npm, pypi, etc.)
     */
    registry: "npm" | "pypi";
    [k: string]: unknown;
  };
  /**
   * Summary statistics for the scanned project
   */
  summary: {
    /**
     * Total number of packages (production + development)
     */
    total_packages: number;
    /**
     * Number of production dependencies
     */
    production_packages: number;
    /**
     * Number of development dependencies
     */
    development_packages: number;
    /**
     * Number of packages with known CVEs
     */
    packages_with_cves: number;
    /**
     * Total number of CVEs across all packages
     */
    total_cves: number;
    /**
     * Number of packages behind the latest version
     */
    packages_outdated: number;
    /**
     * EPSSg over every distinct scored package in the project, direct and transitive
     */
    project_epss?: number | null;
    /**
     * Number of distinct packages contributing to project_epss
     */
    packages_with_epss?: number;
    /**
     * Number of packages with a CVE where no CVE carries an EPSS score
     */
    packages_with_unscored_cves?: number;
    /**
     * Distinct packages whose upstream repository was measured
     */
    packages_with_stability?: number;
    /**
     * Assessed packages whose most probable state is abandoned or deprecated
     */
    packages_unmaintained?: number;
    /**
     * Assessed packages whose most probable state is deprecated
     */
    packages_deprecated?: number;
    /**
     * Packages with no measurement: no repository URL, a non-GitHub host, or statistics unavailable
     */
    packages_stability_unknown?: number;
    [k: string]: unknown;
  };
  /**
   * Production dependency metrics
   */
  production_packages: PackageMetrics[];
  /**
   * Development dependency metrics
   */
  development_packages: PackageMetrics[];
  /**
   * Transitive dependency metrics, one entry per unique (package_name, installed_version); path and constraint data lives in dependency_tree
   */
  transitive_packages: TransitivePackageMetrics[];
  /**
   * Dependency tree rooted at each direct production dependency; nodes carry edge-specific constraint data and reference transitive_packages by id
   */
  dependency_tree: DependencyTreeRoot[];
  /**
   * Lookup table for ct integer field in DependencyTreeNode; index 0=DECLARED, 1=NARROWED, 2=PINNED, 3=ADDITIVE, 4=OVERRIDE
   *
   * @minItems 5
   * @maxItems 5
   */
  constraint_type_map: [string, string, string, string, string];
  [k: string]: unknown;
}
/**
 * Metrics for a single package (used for production and development dependencies)
 */
export interface PackageMetrics {
  /**
   * Package name (canonical registry name)
   */
  package_name: string;
  /**
   * Alias name as declared in the project manifest (null or same as package_name when no alias is used)
   */
  dependency_name?: string | null;
  /**
   * Whether this is a development/optional dependency
   */
  is_optional_dependency: boolean;
  /**
   * Currently installed version
   */
  installed_version: string;
  /**
   * Latest available version
   */
  latest_version: string | null;
  /**
   * Days between installed and latest version
   */
  time_lag_days: number | null;
  /**
   * Days since the installed version was published to the registry
   */
  version_age_days: number | null;
  /**
   * Number of releases between installed and latest
   */
  releases_lag: number | null;
  /**
   * Known CVEs for this package
   */
  cve: CVEInfo[];
  /**
   * Ancestor chain from root to this package (null for direct dependencies)
   */
  dependency_path?: string[] | null;
  /**
   * Version constraint declared in the project manifest (e.g. '^1.2.3', '>=1.0,<2.0')
   */
  version_constraint?: string | null;
  /**
   * Source code repository URL
   */
  repo_url?: string | null;
  /**
   * Package homepage URL
   */
  homepage_url?: string | null;
  /**
   * Package registry page URL
   */
  package_url?: string | null;
  /**
   * SPDX license identifiers parsed from the package license expression
   */
  license?: string[] | null;
  /**
   * Package URL (PURL) per ECMA-386, e.g. pkg:pypi/requests@2.25.1 or pkg:npm/lodash@4.17.21
   */
  purl?: string | null;
  /**
   * How the version constraint was applied: DECLARED (loose/default spec), NARROWED (explicit range with bounds), PINNED (exact version), ADDITIVE (narrows via constraints file), or OVERRIDE (forces a version regardless of other requirements)
   */
  constraint_type?: "DECLARED" | "NARROWED" | "PINNED" | "ADDITIVE" | "OVERRIDE" | null;
  /**
   * File that introduced a non-DECLARED constraint (e.g. 'package.json' for npm overrides, 'pyproject.toml' for uv, 'requirements.txt' for pip classic)
   */
  constraint_source_file?: string | null;
  /**
   * PyPI extras requested for this dependency (e.g. ["security", "tests"] from requests[security,tests]); null for non-PyPI or when no extras are used
   */
  extras?: string[] | null;
  /**
   * Solver-recommended version; null when the package is already at the optimal version
   */
  recommended_version?: string | null;
  /**
   * Whether the installed version is a pre-release (alpha/beta/rc/dev)
   */
  is_prerelease: boolean;
  /**
   * Whether the installed version has been yanked or unpublished from the registry
   */
  is_yanked: boolean;
  /**
   * Whether the installed package or version is deprecated (npm-only; false otherwise)
   */
  is_deprecated: boolean;
  /**
   * Whether the entire package has been removed from the registry (npm-only; false otherwise)
   */
  is_package_unpublished: boolean;
  /**
   * Transitive dependency impacts projected from the recommended update
   */
  update_transitive_impacts?: TransitiveImpactExport[];
  /**
   * Highest EPSS score among this package's CVEs
   */
  epss?: number | null;
  /**
   * Whether the installed version executes arbitrary code during install
   */
  runs_code_at_install?: boolean | null;
  /**
   * Human-readable reason for runs_code_at_install; null when unknown or not detected
   */
  install_execution_reason?: string | null;
  /**
   * Fraction of the maintenance observations that were available
   */
  maintenance_coverage?: number | null;
  /**
   * P(abandoned) + P(deprecated) from the maintenance-state model; the value that feeds triage
   */
  maintenance_risk?: number | null;
  /**
   * Most probable maintenance state
   */
  maintenance_state?: "maintained" | "winding_down" | "abandoned" | "deprecated" | null;
  /**
   * Direction of the issue/PR flow ratio over the engagement window
   */
  flow_trend?: "improving" | "stable" | "declining" | null;
  /**
   * Explicit end-of-life markers found for the package
   */
  deprecation_signals?: string[];
  /**
   * Replacement package named in the metadata / deprecation message / README
   */
  deprecation_successor?: string | null;
  /**
   * Coefficient of variation of inter-commit gaps from the last 100 commits; volume-free, unlike a weekly-bucket CV. Null below 20 sampled gaps
   */
  gap_cv?: number | null;
  /**
   * Median inter-commit gap, in days, from the sampled commits
   */
  median_gap_days?: number | null;
  /**
   * Days since the most recent sampled commit
   */
  silence_days?: number | null;
  /**
   * Empirical probability, from this repository's own gap history, of a silence this long
   */
  silence_p?: number | null;
  /**
   * Non-bot commits that entered the gap measurement
   */
  commits_sampled?: number | null;
  /**
   * Time span, in days, covered by the sampled commits
   */
  span_days?: number | null;
  /**
   * Days since the last push to the upstream repository
   */
  days_since_push?: number | null;
  /**
   * Whether the upstream repository is archived
   */
  archived?: boolean | null;
  /**
   * Recommended action from the EPSS x maintenance matrix
   */
  triage_action?: "evict" | "patch" | "refactor" | "retain" | null;
  [k: string]: unknown;
}
/**
 * CVE information for a package
 */
export interface CVEInfo {
  /**
   * Primary CVE identifier
   */
  id: string;
  /**
   * All aliases (CVE, GHSA, OSV)
   */
  cve_ids: string[];
  /**
   * CVE database source
   */
  source: string;
  /**
   * Affected package name
   */
  package_name: string;
  /**
   * Package registry (npm, pypi, etc.)
   */
  package_registry: string;
  /**
   * Vulnerability description
   */
  summary: string;
  /**
   * Severity level
   */
  severity: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
  /**
   * List of affected versions
   */
  affected_versions: string[];
  /**
   * Publication date
   */
  published: string | null;
  /**
   * URL to upstream advisory
   */
  link: string;
  /**
   * EPSS exploitation probability score, 0-1
   */
  epss?: number | null;
  /**
   * Days a fix has been available; null when no fix is known
   */
  fix_age_days?: number | null;
  [k: string]: unknown;
}
/**
 * Transitive impact of a direct dependency update on a single transitive package
 */
export interface TransitiveImpactExport {
  /**
   * Canonical name of the affected transitive package
   */
  package_name: string;
  /**
   * Currently installed version; null for brand-new transitive deps not in the current tree
   */
  current_version?: string | null;
  /**
   * Best version satisfying all merged constraints; null when no version satisfies (hard conflict)
   */
  projected_version?: string | null;
  /**
   * Constraint the updated direct dependency imposes on this transitive dependency
   */
  new_constraint: string;
  /**
   * Canonical name of the direct dependency recommendation driving this impact
   */
  driven_by: string;
  /**
   * True when projected_version violates an existing parent constraint
   */
  has_conflict: boolean;
  /**
   * Human-readable conflict description
   */
  conflict_detail?: string | null;
  [k: string]: unknown;
}
/**
 * Metrics for a transitive package, deduplicated by (package_name, installed_version); path and constraint data lives in dependency_tree
 */
export interface TransitivePackageMetrics {
  /**
   * Zero-based index into the transitive_packages array; matched by DependencyTreeNode.ref
   */
  id: number;
  /**
   * Package name (canonical registry name)
   */
  package_name: string;
  /**
   * Whether this is a development/optional dependency; always false for transitive deps
   */
  is_optional_dependency: boolean;
  /**
   * Currently installed version
   */
  installed_version: string;
  /**
   * Latest available version
   */
  latest_version: string | null;
  /**
   * Days between installed and latest version
   */
  time_lag_days: number | null;
  /**
   * Days since the installed version was published to the registry
   */
  version_age_days?: number | null;
  /**
   * Number of releases between installed and latest
   */
  releases_lag: number | null;
  /**
   * Known CVEs for this package (absent when empty)
   */
  cve?: CVEInfo[];
  /**
   * File that introduced a non-DECLARED constraint for this package (absent when DECLARED)
   */
  constraint_source_file?: string;
  /**
   * Source code repository URL
   */
  repo_url?: string | null;
  /**
   * Package homepage URL
   */
  homepage_url?: string | null;
  /**
   * Package registry page URL
   */
  package_url?: string | null;
  /**
   * SPDX license identifiers parsed from the package license expression
   */
  license?: string[] | null;
  /**
   * Package URL (PURL) per ECMA-386, e.g. pkg:pypi/requests@2.25.1 or pkg:npm/lodash@4.17.21
   */
  purl?: string | null;
  /**
   * Whether the installed version is a pre-release (alpha/beta/rc/dev)
   */
  is_prerelease: boolean;
  /**
   * Whether the installed version has been yanked or unpublished from the registry
   */
  is_yanked: boolean;
  /**
   * Whether the installed package or version is deprecated (npm-only; false otherwise)
   */
  is_deprecated: boolean;
  /**
   * Whether the entire package has been removed from the registry (npm-only; false otherwise)
   */
  is_package_unpublished: boolean;
  /**
   * Highest EPSS score among this package's CVEs
   */
  epss?: number | null;
  /**
   * Whether the installed version executes arbitrary code during install
   */
  runs_code_at_install?: boolean | null;
  /**
   * Human-readable reason for runs_code_at_install; null when unknown or not detected
   */
  install_execution_reason?: string | null;
  /**
   * Fraction of the maintenance observations that were available
   */
  maintenance_coverage?: number | null;
  /**
   * P(abandoned) + P(deprecated) from the maintenance-state model; the value that feeds triage
   */
  maintenance_risk?: number | null;
  /**
   * Most probable maintenance state
   */
  maintenance_state?: "maintained" | "winding_down" | "abandoned" | "deprecated" | null;
  /**
   * Direction of the issue/PR flow ratio over the engagement window
   */
  flow_trend?: "improving" | "stable" | "declining" | null;
  /**
   * Explicit end-of-life markers found for the package
   */
  deprecation_signals?: string[];
  /**
   * Replacement package named in the metadata / deprecation message / README
   */
  deprecation_successor?: string | null;
  /**
   * Coefficient of variation of inter-commit gaps from the last 100 commits; volume-free, unlike a weekly-bucket CV. Null below 20 sampled gaps
   */
  gap_cv?: number | null;
  /**
   * Median inter-commit gap, in days, from the sampled commits
   */
  median_gap_days?: number | null;
  /**
   * Days since the most recent sampled commit
   */
  silence_days?: number | null;
  /**
   * Empirical probability, from this repository's own gap history, of a silence this long
   */
  silence_p?: number | null;
  /**
   * Non-bot commits that entered the gap measurement
   */
  commits_sampled?: number | null;
  /**
   * Time span, in days, covered by the sampled commits
   */
  span_days?: number | null;
  /**
   * Days since the last push to the upstream repository
   */
  days_since_push?: number | null;
  /**
   * Whether the upstream repository is archived
   */
  archived?: boolean | null;
  /**
   * Recommended action from the EPSS x maintenance matrix
   */
  triage_action?: "evict" | "patch" | "refactor" | "retain" | null;
  [k: string]: unknown;
}
/**
 * Root entry in the dependency tree, anchored at a direct production dependency
 */
export interface DependencyTreeRoot {
  /**
   * Name of the direct production dependency
   */
  package_name: string;
  /**
   * Transitive packages directly required by this production dependency
   */
  children?: DependencyTreeNode[];
  [k: string]: unknown;
}
/**
 * One node in the dependency tree; ref matches id in transitive_packages, ct indexes into constraint_type_map
 */
export interface DependencyTreeNode {
  /**
   * Matches the id field of a TransitivePackageMetrics entry
   */
  ref: number;
  /**
   * Index into the top-level constraint_type_map array
   */
  ct: number;
  /**
   * Version constraint declared by the immediate parent
   */
  version_constraint?: string;
  /**
   * Alias name declared by the immediate parent (absent when same as package_name)
   */
  dependency_name?: string;
  /**
   * PyPI extras for this dependency (absent for non-PyPI or when unused)
   */
  extras?: string[];
  /**
   * Transitive packages directly required by this package
   */
  children?: DependencyTreeNode[];
  [k: string]: unknown;
}
