"""Tests for npm_range — node-semver's range algorithm, held to node-semver's own verdicts.

node_semver_conformance.json is generated by node_semver_conformance.js from a real node-semver
checkout; every range in it is checked for its desugared form, its minimum version, and its
verdict on the versions around each of its bounds, with and without includePrerelease.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pytest
from lark import Token, Tree
from lark.exceptions import UnexpectedInput

from ossiq.solver.npm_range import LOOSE_RANGE_PARSER, RANGE_PARSER, desugar, parse_loose_semver, parse_npm_range

CONFORMANCE: dict[str, Any] = json.loads((Path(__file__).parent / "node_semver_conformance.json").read_text())


def range_id(entry: dict[str, Any]) -> str:
    return repr(entry["range"])[:60]


def node_valid_range(text: str, include_prerelease: bool) -> str | None:
    """`parse_npm_range` printed as node-semver's validRange prints it: None if invalid, "*" for any."""
    try:
        return str(parse_npm_range(text, include_prerelease)) or "*"
    except ValueError:
        return None


def satisfies(text: str, version: str, include_prerelease: bool) -> bool:
    """node-semver's `satisfies`: an unparseable version satisfies nothing."""
    try:
        candidate = parse_loose_semver(version)
    except ValueError:
        return False
    return parse_npm_range(text, include_prerelease).satisfied_by(candidate)


@pytest.mark.parametrize("entry", CONFORMANCE["ranges"], ids=range_id)
def test_range_matches_node_semver(entry: dict[str, Any]) -> None:
    text = entry["range"]
    assert node_valid_range(text, False) == entry["parsed"]
    assert node_valid_range(text, True) == entry["parsed_prerelease"]
    if entry["parsed"] is None:
        return

    min_version = parse_npm_range(text).min_version()
    assert (None if min_version is None else str(min_version)) == entry["min_version"]

    for include_prerelease, key in ((False, "satisfies"), (True, "satisfies_prerelease")):
        expected = {version: verdict == "1" for version, verdict in zip(entry["versions"], entry[key], strict=True)}
        actual = {version: satisfies(text, version, include_prerelease) for version in entry["versions"]}
        mismatches = {version: verdict for version, verdict in expected.items() if actual[version] != verdict}
        assert not mismatches, f"{text!r} include_prerelease={include_prerelease}: node-semver says {mismatches}"


def desugared_or_error(tree: Tree[Token], include_prerelease: bool) -> object:
    try:
        return desugar(tree, include_prerelease)
    except ValueError as error:
        return type(error)


@pytest.mark.parametrize("entry", CONFORMANCE["ranges"], ids=range_id)
def test_lalr_and_earley_agree(entry: dict[str, Any]) -> None:
    """Earley only reads what LALR rejects, so wherever LALR reads a range the two must agree."""
    text = " ".join(entry["range"].split())
    try:
        lalr_tree = RANGE_PARSER.parse(text, start="range")
    except UnexpectedInput:
        return
    earley_tree = LOOSE_RANGE_PARSER.parse(text)
    for include_prerelease in (False, True):
        assert desugared_or_error(lalr_tree, include_prerelease) == desugared_or_error(earley_tree, include_prerelease)


@pytest.mark.parametrize(
    ("text", "desugared"),
    [
        ("1.2.3.4 || ^1", ">=1.0.0 <2.0.0-0"),
        (">=latest || ^1", ">=1.0.0 <2.0.0-0"),
        ("^1 1.2.3.4", ">=1.0.0 <2.0.0-0"),
        # Not a hyphen range: that has to be the whole branch, so the "-" is a junk word.
        ("1.2.3 - 2 3", "1.2.3 >=2.0.0 <3.0.0-0 >=3.0.0 <4.0.0-0"),
    ],
)
def test_earley_drops_the_junk_word_lalr_stops_at(text: str, desugared: str) -> None:
    with pytest.raises(UnexpectedInput):
        RANGE_PARSER.parse(text, start="range")
    assert str(parse_npm_range(text)) == desugared


@pytest.mark.parametrize(
    "pair", CONFORMANCE["fixture_pairs"], ids=lambda pair: f"{pair['range']!r}@{pair['version']!r}"[:60]
)
def test_fixture_pair_matches_node_semver(pair: dict[str, Any]) -> None:
    assert satisfies(pair["range"], pair["version"], pair["include_prerelease"]) == pair["satisfies"]


@pytest.mark.parametrize(("raw", "expected"), CONFORMANCE["versions"].items())
def test_version_parse_matches_node_semver(raw: str, expected: str | None) -> None:
    try:
        parsed = str(parse_loose_semver(raw).replace(build=None))
    except ValueError:
        parsed = None
    assert parsed == expected


# The rules the conformance data covers, spelled out where a reader can see them.
@pytest.mark.parametrize(
    ("text", "desugared"),
    [
        # A missing component is a wildcard: "1" is "1.x.x", not "=1.0.0".
        ("1.2", ">=1.2.0 <1.3.0-0"),
        (">1", ">=2.0.0"),
        ("<=1.2", "<1.3.0-0"),
        # Comparator X-ranges — univers crashed on ">=14.x" and misread the spaced form.
        (">=14.x", ">=14.0.0"),
        (">= 14.x", ">=14.0.0"),
        (">14.x", ">=15.0.0"),
        # Below 1.0.0 a caret holds the first non-zero component.
        ("^0.x", "<1.0.0-0"),
        ("^0.1.2", ">=0.1.2 <0.2.0-0"),
        ("^0.0.3", ">=0.0.3 <0.0.4-0"),
        # node-semver tests the text "00" against "0" and so holds the major; here zero is zero.
        ("^00.1.2", ">=0.1.2 <0.2.0-0"),
        # Each || branch stands alone; univers flattened "~5.5.8 || ~5.5.10" into one set.
        ("~5.5.8 || ~5.5.10", ">=5.5.8 <5.6.0-0||>=5.5.10 <5.6.0-0"),
        ("1.2 - 2", ">=1.2.0 <3.0.0-0"),
        ("", ""),
        ("latest || ^1", ">=1.0.0 <2.0.0-0"),
    ],
)
def test_desugars_to_plain_comparators(text: str, desugared: str) -> None:
    assert str(parse_npm_range(text)) == desugared


@pytest.mark.parametrize(
    ("text", "version", "expected"),
    [
        # A prerelease satisfies a range only when the range names a prerelease of the same
        # major.minor.patch, so ^2.0.0-beta.1 keeps tracking the 2.0.0 betas and nothing else.
        ("^2.0.0-beta.1", "2.0.0-beta.3", True),
        ("^2.0.0-beta.1", "2.1.0-beta.1", False),
        (">=1.2.0", "1.3.0-rc.1", False),
    ],
)
def test_prerelease_needs_a_same_release_bound(text: str, version: str, expected: bool) -> None:
    assert parse_npm_range(text).satisfied_by(parse_loose_semver(version)) is expected


@pytest.mark.parametrize("text", ["!=1.0.0", "latest", "1.x.5", "^9007199254740991.0.0", "garbage || nonsense"])
def test_invalid_range_raises(text: str) -> None:
    with pytest.raises(ValueError):
        parse_npm_range(text)
